##numpy array and basic

learn about numpy ith chai aur code

In [3]:
import  numpy as np

### creating array from list

In [4]:
ar_1d = np.array([1, 2, 3, 4])
print("1D array; ", ar_1d)

1D array;  [1 2 3 4]


In [13]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array; ", arr_2d)

2D array;  [[1 2 3]
 [4 5 6]]


## list vs numpy

In [17]:
py_list = [1,2,3]
print("python list multiplication", py_list * 2)

np_array = np.array([1,2,3])
print("numpy array multiplication", np_array * 2)

import time
start_time = time.time()
py_list = [i*2 for i in range(1000000)]
    
print("Time taken for python list multiplication: ", time.time() - start_time)

start_time = time.time()
np_array = np.arange(1000000) * 2
print("\n numpy operation time: ", time.time() - start_time)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]
Time taken for python list multiplication:  0.02118229866027832

 numpy operation time:  0.0007953643798828125


##creating array from scratch

In [22]:
zeros = np.zeros((3, 4))
print("zero array: \n", zeros)

ones = np.ones((2, 3))
print("one array: \n", ones)

full = np.full((2,2),7)
print("full array: \n",full)

random = np.random.random((2,3))
print("random array: \n",random)

sequence = np.arange(0, 10, 2)
print('sequance array: \n',sequence)

zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.24801551 0.01588966 0.11780443]
 [0.32046515 0.39493699 0.65372821]]
sequance array: 
 [0 2 4 6 8]


### vecctor,matrix,tensor

In [23]:
vector = np.array([1, 2, 3])
print("vector: ", vector)

matrix = np.array([[1, 2, 3],[4, 5, 6]])
print("vector: ", vector)

tensor = np.array([[[1,2,3],[4,5,6]],[[7,5,4],[2,3,5]]])
print("tensor: ", tensor)

vector:  [1 2 3]
vector:  [1 2 3]
tensor:  [[[1 2 3]
  [4 5 6]]

 [[7 5 4]
  [2 3 5]]]


###array properties

In [24]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,5,4],[2,3,5]]])
print("shape: ", tensor.shape)
print("dimension: ", tensor.ndim)
print("size: ", tensor.size)
print("dtype: ", tensor.dtype)

shape:  (2, 2, 3)
dimension:  3
size:  12
dtype:  int64


###array reshaping


In [28]:
arr = np.arange(12)
print("origanal array", arr)

reshaped = arr.reshape((3, 4))
print("reshaped array", reshaped)

flattened =reshaped.flatten()
print("\n flattened array", flattened)

#ravel (returns view insted of copy)

raveled = reshaped.ravel()
print("\n raveled array", raveled)

origanal array [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array [ 0  1  2  3  4  5  6  7  8  9 10 11]


###transpode



In [29]:
transpode = reshaped.T
print("\n raveled array", transpode)


 raveled array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
