###indexing and slicing

In [1]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("basic slicing", arr[2:7])
print("with step", arr[1:8:2])
print("negative indexing", arr[-3])


basic slicing [3 4 5 6 7]
with step [2 4 6 8]
negative indexing 8


2D array

In [9]:
arr_2d = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print("print specific element", arr_2d[1,2])
print("entire row", arr_2d[1])
print("entire column", arr_2d[:,2])


print specific element 6
entire row [4 5 6]
entire column [3 6 9]


###soarting

In [13]:
unsoarted = np.array([3, 4, 5, 6, 1, 8, 9, 24])
print("sorted array", np.sort(unsoarted))

arr_2dunsoarted = ([3,4],[4,3],[5,6])
print("sorted 2d array by column", np.sort(arr_2dunsoarted, axis=0))
print("sorted 2d array by column", np.sort(arr_2dunsoarted, axis=1))

sorted array [ 1  3  4  5  6  8  9 24]
sorted 2d array by column [[3 3]
 [4 4]
 [5 6]]
sorted 2d array by column [[3 4]
 [3 4]
 [5 6]]


###filtering

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_numbers = numbers[numbers % 2 == 0]
print("even numbers", even_numbers)

even numbers [ 2  4  6  8 10]


###filtering with mask

In [ ]:
mask = numbers > 5
print("numbers grater than 5", numbers[mask])

mask [ 6  7  8  9 10]


###fancy indexing vs np.where()

In [7]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("indices of numbers greater than 5", where_result)
print("np where", numbers[where_result])

[1 3 5]
indices of numbers greater than 5 (array([5, 6, 7, 8, 9]),)
np where [ 6  7  8  9 10]


In [7]:
condition_array = np.where(numbers > 5, numbers * 1, numbers)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, numbers * 2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


In [ ]:
###adding and removing data

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

adding = arr1 + arr2
print(adding)

combined = np.concatenate(arr1, arr2)
print(combined)



[5 7 9]


In [ ]:
### array compatibility

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("compatibility shapes", a.shape == b.shape)

compatibility shapes True


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 4])
c = np.array([7, 8, 9])

print("compatibility shapes", a.shape == b.shape)

compatibility shapes False


In [24]:
original = np.array([[1,2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))
print(original)
print(with_new_row)



[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]


In [23]:
new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2 7]
 [3 4 8]]


In [25]:
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr, 2)
print("array after deletion: ", deleted)

array after deletion:  [1 2 4 5]
